name: Hola mundo

on:
  workflow_dispatch: # ejecución manual
 # push:
 #   branches:
 #     - main
  #  paths:
   #   - 'BibliotecaAPI/**'
    #  - 'BibliotecaAPITests/**'
     # - '.github/workflows/hola-mundo.yml'
  #pull_request:
   # branches:
    #  - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Felipe"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree